/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    GlobalLayout: typeof import('./src/components/GlobalLayout/GlobalLayout.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld/HelloWorld.vue')['default']
    LocaleSwitcher: typeof import('./src/components/LocaleSwitcher/LocaleSwitcher.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeLayoutSwitcher: typeof import('./src/domains/Theme/components/ThemeSwitcher/ThemeLayoutSwitcher.vue')['default']
    ThemeSwitcher: typeof import('./src/domains/Theme/components/ThemeSwitcher/ThemeSwitcher.vue')['default']
  }
}
