/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ControlsProvider: typeof import('./src/histoire/ControlsProvider/ControlsProvider.vue')['default']
    HypButton: typeof import('./src/lib/HypButton/HypButton.vue')['default']
    'HypButton.story': typeof import('./src/lib/HypButton/HypButton.story.vue')['default']
    HypTypo: typeof import('./src/lib/HypTypo/HypTypo.vue')['default']
    'HypTypo.story': typeof import('./src/lib/HypTypo/HypTypo.story.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
