/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    'Colors.story': typeof import('./src/lib/designTokens/Colors/Colors.story.vue')['default']
    ControlsProvider: typeof import('./src/histoire/ControlsProvider/ControlsProvider.vue')['default']
    HypButton: typeof import('./src/lib/base/HypButton/HypButton.vue')['default']
    'HypButton.story': typeof import('./src/lib/base/HypButton/HypButton.story.vue')['default']
    HypIcon: typeof import('./src/lib/base/HypIcon/HypIcon.vue')['default']
    'HypIcon.story': typeof import('./src/lib/base/HypIcon/HypIcon.story.vue')['default']
    HypInput: typeof import('./src/lib/form/HypInput/HypInput.vue')['default']
    'HypInput.story': typeof import('./src/lib/form/HypInput/HypInput.story.vue')['default']
    HypLink: typeof import('./src/lib/base/HypLink/HypLink.vue')['default']
    'HypLink.story': typeof import('./src/lib/base/HypLink/HypLink.story.vue')['default']
    HypTypo: typeof import('./src/lib/base/HypTypo/HypTypo.vue')['default']
    'HypTypo.story': typeof import('./src/lib/base/HypTypo/HypTypo.story.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TokenColor: typeof import('./src/histoire/Token/TokenColor.vue')['default']
    TokenColorList: typeof import('./src/histoire/Token/TokenColorList.vue')['default']
  }
}
