name: 'install'
description: 'Install yarn dependencies'

inputs:
  node_version:
    description: 'Node version'
    required: true
  context: 
    description: 'Context application'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Use Node.js ${{ inputs.node_version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node_version }}
    - name: Run install
      run: |
        if [[ "${{ inputs.context }}" == "admin" ]]; then
          yarn admin:install
        fi
        if [[ "${{ inputs.context }}" == "components" ]]; then
          yarn components:install
        fi
      shell: bash
