name: 'Lint'
description: 'Lint code'

inputs:
  node_version:
    description: 'Node version'
    required: true
  context: 
    description: 'Context application'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout Commit
      uses: actions/checkout@v4
    - name: Use Node.js ${{ inputs.node_version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node_version }}
        cache: 'yarn'
    - run: yarn install --frozen-lockfile
      shell: bash
    - name: Run lint
      run: |
        if [[ "${{ inputs.context }}" == "admin" ]]; then
          yarn admin:lint
        fi
        if ${{ inputs.context }} == "components" ]]; then
          yarn components:lint
        fi
      shell: bash
